### PR TITLE
[view] [test] finishing #21

### PR DESCRIPTION
**Pull request by wolfbiter**
i have three remaining TODO questions in the code:
1. https://github.com/wolfbiter/resources/blob/master/view/test/middle-tests.js#L112
2. https://github.com/wolfbiter/resources/blob/master/view/test/tests.js#L88
3. https://github.com/wolfbiter/resources/blob/master/view/test/tests.js#L137

2 and 3 are essentially the same. let me know what you think.

### CODE REVIEW

**Comment by Marak** [comment]
@wolfbiter -
1. No. The presenter should traverse up until it finds the first parent with a layout presenter.
2. Yes. Sometimes a developer might just want to just write JS ( starting with an empty template ) .
3. Yes. Same as above. Developer might want to just write JS.

**Comment by ahdinosaur** [comment]
@Marak can there be a way to .present without a layout? layouts are no good for embedding presenters within presenters that already have a layout.

**Comment by wolfbiter** [comment]
@Marak -
wait if (1) is as you say then the unit tests for view itself are wrong:
https://github.com/wolfbiter/resources/blob/master/view/test/tests.js#L332

currently the way that view behaves is that layouts only apply to views in the same directory as the layout (meaning layouts don't nest/stack).

ahdinosaur and i have been leveraging this fact in the app we are developing... if this is changing then we need "a way to .present without a layout"

**Comment by ahdinosaur** [comment]
after more work on [bigspace](https://github.com/ahdinosaur/bigspace), i think i've reached a little better understanding of what view should be.
- [x] [task] yes to "The presenter should traverse up until it finds the first parent with a layout presenter". still needs to be implemented.
- [x] [design]: you should have an option to explicitly not use a layout, even if one exists. we temporarily needed this so we made up (layout: false) as a parameter to signify this and hacked together https://github.com/ahdinosaur/bigspace/blob/master/resources/view/lib/View.js#L213. although we no longer use it, i still think it is useful and we might in the future. another option is for this to be explicitly handled in the presenter by re-loading with `var $ = this.$.load(this.template)`.
- [x] [design]: yes to nested layouts, such as if you .present in a .present... haven't figured out a good solution for a better id="main" to handle this, but initial thoughts are basing it around the resource and/or directory name that a layout is in. another thought is that maybe we specify each layout invocation individually in the presenter as a function call. this might be the easiest way to get the most power, although at a cost to simplicity.

**Comment by wolfbiter** [comment]
- [ ] views should be created for presenters without templates (ie a js file with no corresponding html)

**Comment by wolfbiter** [comment]
all tests have been fixed and are passing. the only remaining TODOs: write the test which breaks prefix (using /.../prefix/.../ ) and the one above

**Comment by wolfbiter** [comment]
code from pull request merged elsewhere

**Pull request closed without merging**
